name: "Bump version"
description: "Run semantic-release to bump version and expose new version"

inputs:
  token:
    description: "Github token to push tags"
    required: true

outputs:
  version:
    description: "The new version after bump"
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        persist-credentials: 'true'
    
    - name: "Bump version & generate changelog"
      id: bump
      shell: bash
      run: |
        poetry run semantic-release version --changelog
    
    - name: "Extract new version"
      id: extract-version
      shell: bash
      run: |
        VERSION=$(poetry run semantic-release version --print)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
