name: "Bump version"
description: "Run semantic-release to bump version and expose new version"

inputs:
  token:
    description: "Github token to push tags"
    required: true

outputs:
  version:
    description: "The new version after bump"
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        persist-credentials: 'true'
    
    - name: "Checkout target branch"
      shell: bash
      run: |
        TARGET_BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
        echo "Checking out branch: $TARGET_BRANCH"
        git fetch origin $TARGET_BRANCH
        git checkout $TARGET_BRANCH
    
    - name: "Bump version & generate changelog"
      id: bump
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        export PATH=$PATH:/root/.local/bin
        poetry run semantic-release version --changelog
    
    - name: "Extract new version"
      id: extract-version
      shell: bash
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        export PATH=$PATH:/root/.local/bin
        VERSION=$(poetry run semantic-release version --print)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
