name: "Bump version"
description: "Run semantic-release to bump version and expose new version"

inputs:
  token:
    description: "Github token to push tags"
    required: true

outputs:
  version:
    description: "The new version after bump"
    value: ${{ steps.extract-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        persist-credentials: 'true'

    - name: "Bump version using semantic-release"
      id: semantic-release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ inputs.token }}

    - name: "Extract new version"
      id: extract-version
      shell: bash
      run: |
        echo "Get the latest tag created by semantic-release ..."
        VERSION=$(git describe --tags --abbrev=0)
        echo "Extracted version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: "Commit new version tag"
      if: steps.extract-version.outputs.version != ''
      shell: bash
      run: |
        VERSION="${{ steps.extract-version.outputs.version }}"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit --allow-empty -m "chore(release): $VERSION"
        git push origin HEAD:${GITHUB_REF_NAME}
