name: "Shared CI workflow"

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      username:
        required: true
        type: string
      password:
        required: true
        type: string
      version:
        required: true
        type: string
      github_token:
        required: true
        type: string

jobs:
  check-quality-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-package@main
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}
      - uses: ./.github/actions/setup-python@main
      - uses: ./.github/actions/quality-code@main

  run-tests:
    needs: [check-quality-code]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cache-package@main
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}
      - uses: ./.github/actions/setup-python@main
      - uses: ./.github/actions/run-tests@main

  bump-version:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bump-version@main
        with:
          token: ${{ inputs.github_token }}

  build-push-image:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set ref info"
        id: ref
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "ref_type=tag" >> $GITHUB_OUTPUT
            echo "ref_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "ref_type=branch" >> $GITHUB_OUTPUT
            echo "ref_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - uses: ./.github/actions/docker-build-push@main
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          version: ${{ needs.bump-version.outputs.version }}
