name: "Shared CI workflow"

on:
  workflow_call:
    secrets:
        GHRC_REGISTRY_ADDR:
            required: true
        GHRC_USERNAME:
            required: true
        GHRC_PASSWORD:
            required: true
        GH_SUBMODULE_TOKEN:
            required: true

jobs:
  check-quality-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/cache-package
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}
      
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/quality-code

  run-tests:
    needs: [check-quality-code]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/cache-package
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/run-tests

  bump-version:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/bump-version
        with:
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}

  build-push-image:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Set ref info"
        id: ref
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "ref_type=tag" >> $GITHUB_OUTPUT
            echo "ref_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "ref_type=branch" >> $GITHUB_OUTPUT
            echo "ref_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      
      - uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ secrets.GHRC_REGISTRY_ADDR }}
          username: ${{ secrets.GHRC_USERNAME }}
          password: ${{ secrets.GHRC_PASSWORD }}
          version: ${{ needs.bump-version.outputs.version }}
