name: "Shared CI workflow"

on:
  workflow_call:
    secrets:
      GHRC_REGISTRY_ADDR:
        required: true
      GHRC_USERNAME:
        required: true
      GHRC_PASSWORD:
        required: true
      GH_SUBMODULE_TOKEN:
        required: true

jobs:
  check-quality-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: flavien-hugs/github-actions-shared/.github/actions/cache-package@main
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}
      
      - uses: flavien-hugs/github-actions-shared/.github/actions/setup-python@main
      - uses: flavien-hugs/github-actions-shared/.github/actions/quality-code@main

  run-tests:
    needs: [check-quality-code]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: flavien-hugs/github-actions-shared/.github/actions/cache-package@main
        with:
          cache-key: ${{ runner.os }}-pip-poetry-${{ hashFiles('**/poetry.lock') }}

      - uses: flavien-hugs/github-actions-shared/.github/actions/setup-python@main
      
      - uses: flavien-hugs/github-actions-shared/.github/actions/run-tests@main
        with:
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}
  
  bump-version:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: flavien-hugs/github-actions-shared/.github/actions/setup-python@main
      - uses: flavien-hugs/github-actions-shared/.github/actions/bump-version@main
        with:
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}

  build-push-image:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_SUBMODULE_TOKEN }}
      
      - uses: flavien-hugs/github-actions-shared/.github/actions/docker-build-push@main
        with:
          registry: ${{ secrets.GHRC_REGISTRY_ADDR }}
          username: ${{ secrets.GHRC_USERNAME }}
          password: ${{ secrets.GHRC_PASSWORD }}
          version: ${{ needs.bump-version.outputs.version }}
